#ifndef EVENT__HH
#define EVENT__HH

#include "config.h"
#include "qp_port.h"

/*****************Macro****************/

/*****************Enum*****************/
//  内部使用的信号
typedef enum
{ /* all signals for the Bomb FSM */
    Q_WORK_TIME_OUT_SIG = Q_USER_SIG,           //4
    Q_FUNCTION_TIME_OUT_SIG,
    Q_WARN_TIME_OUT_SIG,
    Q_KEY_BOARD_PRESS_SIG,
    Q_KEY_PRESS_SIG,
    Q_KEY_BOARD_RELEASE_SIG,
    Q_HANDLE_SIG,
    Q_USER_HANDLE_SIG,
    Q_USER_KEY_SIG,
    Q_NFC_KEY_SIG,
    
    Q_SIG_CNT,

    EVENT_SIG_NULL = 0xFF,

}LockSignals;

typedef enum{
    USER_EVENT_SUCCESS = 0,
    USER_EVENT_SUCCESS_VERIFY_ADMIN,
    USER_EVENT_SUCCESS_VERIFY_USER,
    
    USER_EVENT_SUCCESS_VERIFY_REGISTER,
    USER_EVENT_SUCCESS_VERIFY_UNLOCK,
    USER_EVENT_SUCCESS_VERIFY_REMOTE_UNLOCK,
    USER_EVENT_SUCCESS_VERIFY_SET_PARAMETER,
    USER_EVENT_SUCCESS_VERIFY_DELETE,

    USER_EVENT_SUCCESS_REGISTER,
    USER_EVENT_SUCCESS_MODIFY,
    USER_EVENT_SUCCESS_DELETE,
    
    USER_EVENT_FAIL,
    USER_EVENT_FAIL_INVALID,
    USER_EVENT_FAIL_INVALID_USER,
    USER_EVENT_FAIL_INVALID_ADMIN,
    USER_EVENT_FAIL_TOO_SHORT,
    USER_EVENT_FAIL_TOO_LONG,
    USER_EVENT_FAIL_FULL,
    USER_EVENT_FAIL_EMPTY,
    USER_EVENT_FAIL_SIMPTY,
    USER_EVENT_FAIL_REPEAT,
    
    EVENT_RESULT_VOICE_TIME_OUT,        //语音播报完毕


    EVENT_RESULT_SUCCESS,
    EVENT_RESULT_SUCCESS_ADD,
    EVENT_RESULT_SUCCESS_VERIFY_ADMIN,
    EVENT_RESULT_SUCCESS_VERIFY_USER,
    EVENT_RESULT_SUCCESS_VERIFY_USER_LOCK,
    EVENT_RESULT_SUCCESS_UNLOCKED,
    EVENT_RESULT_SUCCESS_LOCKED,
    EVENT_RESULT_SUCCESS_RESET,     //复位成功
    EVENT_RESULT_SUCCESS_SETUP,     //设置成功
    EVENT_RESULT_MOTOR_RESET_SUCCESS,//电机自校准成功
    EVENT_RESULT_FAIL,
    EVENT_RESULT_FAIL_ADD,
    EVENT_RESULT_FAIL_TOO_SIMPLE,   // 密码过于简单
    EVENT_RESULT_FAIL_INVALID,
    EVENT_RESULT_FAIL_ID_DEL,       //指纹有ID，锁控没有
    EVENT_RESULT_FAIL_TOO_SHORT,
    EVENT_RESULT_FAIL_TOO_LONG,
    EVENT_RESULT_FAIL_FULL,
    EVENT_RESULT_FAIL_REPEAT,
    EVENT_RESULT_FAIL_CARD_REPEAT,
    EVENT_RESULT_FAIL_EMPTY,
    EVENT_RESULT_FAIL_SIMPLY,
    EVENT_RESULT_FAIL_INPUT,
    EVENT_RESULT_FAIL_DIFFERENT,        //输入不一样
    EVENT_RESULT_BACK_MENU,
    EVENT_RESULT_EXIT_MENU,             //退出菜单
    EVENT_RESULT_REPEAT_MENU,           //重新进入状态机
    EVENT_RESULT_DELETION_FAIL,         //删除失败
    EVENT_RESULT_VACATION_MODE_FAIL,    //离家模式
    EVENT_RESULT_WAKE,
    EVENT_RESULT_TOUCH_WAKE,            //触摸唤醒
    EVENT_RESULT_LOCK,
    EVENT_RESULT_KEY_LOCK,              //按键关锁事件
    EVENT_RESULT_RESET_LONG_PRESS,      //复位按键长按
    EVENT_RESULT_RESET_RELEASE,         //复位按键松手
    EVENT_RESULT_RESET_TEST,
    EVENT_RESULT_KEY_LONG_PRESS_RELEASE,
    EVENT_RESULT_RESET_LONG_PRESS_RELEASE,
    EVENT_RESULT_FINGERPRINT_PRESS,
    EVENT_RESULT_VACATION_MODE_WARN,
    EVENT_RESULT_VERSION,
    EVENT_RESULT_TIME,
    //produce test
    EVENT_RESULT_SLEEP,
    EVENT_RESULT_AGING_TEST,
    EVENT_RESULT_AGING_TEST_TIME,
    EVENT_RESULT_DEVICE_TEST_STEP1,
    EVENT_RESULT_DEVICE_TEST_STEP2,
    EVENT_RESULT_PRODUCE_TEST,
    EVENT_RESULT_MOTOR_TEST,
    EVENT_RESULT_KEY_BOARD_TEST,
    EVENT_RESULT_NFC_TEST,
    EVENT_RESULT_MOTOR_TEST_SUCCESS,
    EVENT_RESULT_MOTOR_TEST_FAIL,
    EVENT_RESULT_DEV_PARA_MODE,
    EVENT_RESULT_DEV_NORMAL_MODE,
    EVENT_RESULT_VERTION_TEST,


    USER_EVENT_CNT,

}user_key_event_e;

typedef enum{
    HANDLE_EVENT_SUCCESS = 0,
    HANDLE_EVENT_FAIL,
    HANDLE_EVENT_WAKE,
    HANDLE_EVENT_TAMPER_WARN,
    HANDLE_EVENT_UART_RX,
    HANDLE_EVENT_SLEEP,
    HANDLE_EVENT_SLEEP_BUSY,
    HANDLE_EVENT_CNT,
}handle_event_e;

/****************Struct****************/


/***************Variable***************/


/***************Function***************/
void baseEventPush(uint8_t event_type, uint8_t value);
void userHandleEventPush(uint8_t result, uint16_t user_sn);
void handleEventPush(uint8_t handle, uint8_t value);
void nfcKeyEventPush(uint8_t* id, uint8_t size);

/**************************************/

#endif 
