SET PATH=Z:\Keil_v5.36\ARM\ARMCC\Bin;Z:\MentorGraphics\9.5PADS\SDD_HOME\common\win32\bin;Z:\MentorGraphics\9.5PADS\SDD_HOME\common\win32\lib;Z:\MentorGraphics\9.5PADS\MGC_HOME.ixn\bin;Z:\MentorGraphics\9.5PADS\MGC_HOME.ixn\lib;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\SinoVoice\jTTS 5.0 Desktop\Bin;Z:\Program Files\Polyspace\R2019a\runtime\win64;Z:\Program Files\Polyspace\R2019a\bin;Z:\Program Files\Polyspace\R2019a\polyspace\bin;Z:\Program Files (x86)\Altium Designer Summer 09\System;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;Z:\Program Files (x86)\Microchip\xc8\v2.05\bin
SET CPU_TYPE=OB90A64M1B
SET CPU_VENDOR=On-Bright
SET UV2_TARGET=39140
SET CPU_CLOCK=0x02FAF080
"Z:\Keil_v5.36\ARM\ARMCC\Bin\ArmCC" --Via "..\build\objects\system_ob90a64m1.__i"
"Z:\Keil_v5.36\ARM\ARMCC\Bin\ArmLink" --Via "..\Build\Objects\ota_app.lnp"
